#cloud-config
package_update: false
package_upgrade: false

write_files:
  - path: /home/chipuser/hello.txt
    permissions: '0644'
    content: |
      Hello poging 2. Nu chipuser in plaats van iac.

runcmd:
  - printf 'Hello poging 2. Nu chipuser in plaats van iac.\n' > /home/chipuser/hello.txt
  - chown chipuser:chipuser /home/chipuser/hello.txt
  - date > /var/tmp/cloud-init-ran.txt
